version: "3"

services:

  redis:
    container_name: redis_container
    image: redis

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python3 manage.py makemigrations &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"


  celery: 
    build:
      context: .
    container_name: celery-worker
    restart: always
    command: sh -c "celery -A send_mail worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
